-- IS455 shop schema (PostgreSQL) — migrated from shop.db SQLite layout
-- Run in Supabase SQL Editor or via `supabase db push`

CREATE TABLE customers (
  customer_id BIGINT PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  gender TEXT NOT NULL,
  birthdate TEXT NOT NULL,
  created_at TEXT NOT NULL,
  city TEXT,
  state TEXT,
  zip_code TEXT,
  customer_segment TEXT,
  loyalty_tier TEXT,
  is_active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE products (
  product_id BIGINT PRIMARY KEY,
  sku TEXT NOT NULL UNIQUE,
  product_name TEXT NOT NULL,
  category TEXT NOT NULL,
  price DOUBLE PRECISION NOT NULL,
  cost DOUBLE PRECISION NOT NULL,
  is_active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE orders (
  order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES customers (customer_id),
  order_datetime TEXT NOT NULL,
  billing_zip TEXT,
  shipping_zip TEXT,
  shipping_state TEXT,
  payment_method TEXT NOT NULL,
  device_type TEXT NOT NULL,
  ip_country TEXT NOT NULL,
  promo_used INTEGER NOT NULL DEFAULT 0,
  promo_code TEXT,
  order_subtotal DOUBLE PRECISION NOT NULL,
  shipping_fee DOUBLE PRECISION NOT NULL,
  tax_amount DOUBLE PRECISION NOT NULL,
  order_total DOUBLE PRECISION NOT NULL,
  risk_score DOUBLE PRECISION NOT NULL,
  is_fraud INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE order_items (
  order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES orders (order_id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products (product_id),
  quantity INTEGER NOT NULL,
  unit_price DOUBLE PRECISION NOT NULL,
  line_total DOUBLE PRECISION NOT NULL
);

CREATE TABLE shipments (
  shipment_id BIGINT PRIMARY KEY,
  order_id BIGINT NOT NULL UNIQUE REFERENCES orders (order_id) ON DELETE CASCADE,
  ship_datetime TEXT NOT NULL,
  carrier TEXT NOT NULL,
  shipping_method TEXT NOT NULL,
  distance_band TEXT NOT NULL,
  promised_days INTEGER NOT NULL,
  actual_days INTEGER NOT NULL,
  late_delivery INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE product_reviews (
  review_id BIGINT PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES customers (customer_id),
  product_id BIGINT NOT NULL REFERENCES products (product_id),
  rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  review_datetime TEXT NOT NULL,
  review_text TEXT,
  UNIQUE (customer_id, product_id)
);

CREATE TABLE order_predictions_fraud (
  order_id BIGINT PRIMARY KEY REFERENCES orders (order_id) ON DELETE CASCADE,
  fraud_probability DOUBLE PRECISION NOT NULL,
  predicted_fraud INTEGER NOT NULL,
  prediction_timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_orders_customer ON orders (customer_id);
CREATE INDEX idx_orders_datetime ON orders (order_datetime);
CREATE INDEX idx_items_order ON order_items (order_id);
CREATE INDEX idx_items_product ON order_items (product_id);
CREATE INDEX idx_shipments_late ON shipments (late_delivery);
CREATE INDEX idx_reviews_product ON product_reviews (product_id);
CREATE INDEX idx_reviews_customer ON product_reviews (customer_id);

-- Fallback scorer when sklearn joblib is not in the serverless runtime (uses operational risk_score)
CREATE OR REPLACE FUNCTION public.refresh_fraud_predictions_fallback()
RETURNS void
LANGUAGE sql
AS $$
  DELETE FROM order_predictions_fraud WHERE order_id IS NOT NULL;
  INSERT INTO order_predictions_fraud (order_id, fraud_probability, predicted_fraud, prediction_timestamp)
  SELECT
    order_id,
    LEAST(1.0::double precision, GREATEST(0.0::double precision, risk_score / 100.0)),
    CASE WHEN risk_score >= 50 THEN 1 ELSE 0 END,
    NOW()
  FROM orders;
$$;

-- Call after bulk seeding so new orders / line items get IDs above existing rows
CREATE OR REPLACE FUNCTION public.reset_shop_sequences()
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  PERFORM setval(
    pg_get_serial_sequence('orders', 'order_id'),
    COALESCE((SELECT MAX(order_id) FROM orders), 1)
  );
  PERFORM setval(
    pg_get_serial_sequence('order_items', 'order_item_id'),
    COALESCE((SELECT MAX(order_item_id) FROM order_items), 1)
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.refresh_fraud_predictions_fallback() TO service_role;
GRANT EXECUTE ON FUNCTION public.reset_shop_sequences() TO service_role;
